[package]
name = "loadsmith"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Mod extraction and (un)installation utilities for a range of mod loaders."
repository = "https://github.com/Kesomannen/loadsmith"
readme = "README.md"
exclude = ["tests/"]

[dependencies]
anyhow = "1.0.100"
glob-match = "0.2.1"
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
thiserror = "2.0.16"
walkdir = "2.5.0"
zip = "5.1.1"
