cargo publish -p loadsmith-util
cargo publish -p loadsmith-core
cargo publish -p loadsmith-install
cargo publish -p loadsmith-loader
cargo publish -p loadsmith-registry
cargo publish -p loadsmith-platform
cargo publish -p loadsmith-thunderstore
cargo publish -p loadsmith-manifest
cargo publish -p loadsmith-github
cargo publish -p loadsmith
