[package]
name = "loadsmith-github"
version = "0.3.1"
edition = "2024"
description = "GitHub Releases registry for the loadsmith mod-manager library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kesomannen/loadsmith"
documentation = "https://docs.rs/loadsmith-github"

[dependencies]
loadsmith-core = { workspace = true }
loadsmith-registry = { workspace = true }

octocrab = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
globset = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
octocrab = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rustls = { version = "0.23.41" }
