[package]
name = "loadsmith-core"
version = "0.3.1"
edition = "2024"
description = "Core types, traits, and errors for the loadsmith mod-manager library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kesomannen/loadsmith"
documentation = "https://docs.rs/loadsmith-core"

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
camino = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
blake3 = { workspace = true }
digest-io = { workspace = true }
walkdir = { workspace = true }
