[package]
name = "loadsmith-registry"
version = "0.3.0"
edition = "2024"
description = "Registry abstraction and built-in sources for the loadsmith mod-manager library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kesomannen/loadsmith"
documentation = "https://docs.rs/loadsmith-registry"

[dependencies]
loadsmith-core = { workspace = true }
loadsmith-util = { workspace = true }

thiserror = { workspace = true }
url = { workspace = true }
tokio = { workspace = true, features = ["full"] }
thunderstore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
digest-io = { workspace = true }
zip = { workspace = true }
camino = { workspace = true }
tracing = { workspace = true }
