[package]
name = "loadsmith-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
loadsmith-core = { path = "../loadsmith-core" }
loadsmith-util = { path = "../loadsmith-util" }

thiserror = { workspace = true }
url = { workspace = true }
tokio = { workspace = true, features = ["full"] }
thunderstore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
digest-io = { workspace = true }
zip = { workspace = true }
camino = { workspace = true }
tracing = { workspace = true }
