[package]
name = "loadsmith-loader-test-helper"
version = "0.3.0"
edition = "2024"
publish = false

[dependencies]
loadsmith-core = { workspace = true }
loadsmith-thunderstore = { workspace = true }

thunderstore = { workspace = true }
zip = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
