[package]
name = "loadsmith-loader-test-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
loadsmith-core = { path = "../loadsmith-core" }
loadsmith-thunderstore = { path = "../loadsmith-thunderstore" }

thunderstore = { workspace = true }
zip = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
