[package]
name = "loadsmith-platform"
version = "0.2.0"
edition = "2024"
description = "Platform and game detection for the loadsmith mod-manager library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kesomannen/loadsmith"
documentation = "https://docs.rs/loadsmith-platform"

[dependencies]
loadsmith-loader = { workspace = true }

steamlocate = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
camino = { workspace = true }
