[package]
name = "loadsmith-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
loadsmith-core = { path = "../loadsmith-core" }
loadsmith-install = { path = "../loadsmith-install" }

camino = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
zip = { workspace = true }
insta = { workspace = true }
