[package]
name = "loadsmith-loader"
version = "0.3.1"
edition = "2024"
description = "Mod loader definitions and launch-argument generation for the loadsmith mod-manager library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Kesomannen/loadsmith"
documentation = "https://docs.rs/loadsmith-loader"

[dependencies]
loadsmith-core = { workspace = true }
loadsmith-install = { workspace = true }
loadsmith-util = { workspace = true }

camino = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }
globset = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
zip = { workspace = true }
insta = { workspace = true }
